import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {Household,SPOTS} from '../dist/simulation.js';import {senses} from '../dist/perception.js';import {SoarController,loadSources} from '../dist/soar/controller.js';import {encodeSave,decodeSave} from '../dist/storage.js';import {buildDayReport,reportForModel} from '../dist/reflection.js';
const sources=await loadSources(p=>fs.readFileSync(new URL('../dist/'+p,import.meta.url),'utf8')),root=await SoarController.create(sources,{wasmBinary:fs.readFileSync(new URL('../dist/soar/soar.wasm',import.meta.url))});
const make=(saved=null)=>new Household(730,saved, {calendar:false,director:false}).attachBrain(new SoarController(root.native,sources));const evidence=[];
function social(s,id,subject,value,domain='help',opts={}){return s.perceive(s.person(id),subject,'reliability',value,{kind:'social',source:'heard',domain,root:`${id}-${subject}-${value}-${domain}`,speaker:subject,goalRelevant:true,...opts});}
function freeze(s){for(const p of s.people){s.release(p);p.nextDecision=1e9;p.hunger=p.energy=p.fun=p.social=90;}}

test('hidden world stock never leaks through facts or candidate filtering',()=>{const a=make(),b=make();try{for(const s of [a,b]){const p=s.person('xing');Object.assign(p,{x:-6,z:-4});s.space.screenClosed=true;p.mental={};p.sensed={};}a.home.food=0;b.home.food=50;a.home.ingredients=0;b.home.ingredients=50;const pa=a.person('xing'),pb=b.person('xing');assert.equal(a.facts(pa).food,b.facts(pb).food);assert.deepEqual(a.affordances(pa).map(x=>x.kind),b.affordances(pb).map(x=>x.kind));assert.ok(a.affordances(pa).some(x=>x.kind==='eat'));a.start(pa,{kind:'eat'});a.beginDoing(pa);assert.equal(pa.action,'idle');assert.equal(a.known(pa,'pot','stock').value,0);evidence.push({case:'hidden-stock',sameCandidates:true,discoveredAtExecution:0});}finally{a.brain.destroy();b.brain.destroy();}});

test('walls, acoustic attenuation and sleeping block information without telepathic participants',()=>{const s=make();try{freeze(s);const a=s.person('xing'),b=s.person('xue');Object.assign(a,{x:0,z:0});Object.assign(b,{x:0,z:-3.4});s.space.screenClosed=true;assert.equal(senses(s,b,a).visible,false);assert.equal(senses(s,b,a).audible,true);assert.equal(senses(s,b,a).understood,false);const m=s.tell(a.id,b.id,{subject:'secret',predicate:'location',value:'book'});assert.equal(m.delivered,false);const sent=s.brain.recall(a.id,{type:'event',kind:'testimony-sent',target:b.id}).memory;assert.equal(sent.delivered,'no');assert.equal(sent.subject,'secret');assert.ok(!s.known(b,'secret','location'));const e=s.emit('refuse',a,'没有听清的拒绝',[b.id]);assert.ok(!e.observedBy.includes(b.id));s.space.screenClosed=false;assert.equal(s.tell(a.id,b.id,{subject:'secret',predicate:'location',value:'book'}).delivered,true);b.action='sleep';assert.equal(s.tell(a.id,b.id,{subject:'asleep-secret',predicate:'location',value:'desk'}).delivered,false);evidence.push({case:'perception-boundary',heardSoundWithoutContent:true,sleepBlocksMessages:true});}finally{s.brain.destroy();}});

test('native Soar retains an old location, searches it, then discovers the changed world',()=>{const s=make();try{freeze(s);const p=s.person('xing');s.perceive(p,'notebook','location','desk');Object.assign(p,{x:-6,z:-4});s.space.screenClosed=true;s.moveObject('notebook','book');assert.equal(s.known(p,'notebook','location').value,'desk');s.seekObject(p.id,'notebook');s.decide(p);assert.equal(p.task.location,'desk');assert.equal(p.decision.rule,'mind*seek-last-known-place');const first=p.task.location;s.space.screenClosed=false;s.advance(40);assert.equal(s.known(p,'notebook','location').value,'book');assert.equal(p.seeking,null);assert.ok(s.events.some(e=>e.type==='inspection'));evidence.push({case:'search-from-belief',first,found:'book',rule:'mind*seek-last-known-place'});}finally{s.brain.destroy();}});

test('testimony keeps provenance, conflict and uncertainty; circular repetition is not corroboration',()=>{const s=make();try{freeze(s);for(const [i,p] of s.people.entries())Object.assign(p,{x:1+i*.2,z:0});const a=s.person('xing'),b=s.person('dad'),c=s.person('xue');s.tell(a.id,b.id,{subject:'letter',predicate:'location',value:'book',root:'original-A'});let rb=s.known(b,'letter','location');assert.equal(rb.status,'tentative');s.tell(b.id,c.id,{subject:'letter',predicate:'location',value:rb.value,root:rb.provenance});assert.equal(s.known(c,'letter','location').provenance,'original-A');s.tell(c.id,b.id,{subject:'letter',predicate:'location',value:'book',root:'original-A'});assert.equal(s.known(b,'letter','location').status,'tentative');assert.deepEqual(s.known(b,'letter','location'),rb);s.tell(a.id,b.id,{subject:'letter',predicate:'location',value:'desk',root:'new-conflict'});assert.equal(s.known(b,'letter','location').status,'disputed');s.perceive(b,'letter','location','desk');assert.equal(s.known(b,'letter','location').status,'known');assert.equal(s.known(b,'letter','location').value,'desk');assert.equal(s.known(b,'letter','location').prior,'book');assert.equal(s.brain.recall(b.id,{type:'event',kind:'testimony',value:'book'}).memory.value,'book');evidence.push({case:'provenance',repeatConfidence:'tentative',conflictPreserved:true,directCorrection:'desk'});}finally{s.brain.destroy();}});

test('same refusal produces personal appraisals and coping, fatigue modulates intensity, no event stacking',()=>{const s=make();try{freeze(s);const x=s.person('xing');const xr=social(s,'xing','me','refuse').record,dr=social(s,'dad','me','refuse').record;assert.equal(xr.coping,'withdraw');assert.equal(dr.coping,'verify');assert.ok(xr.intensity>dr.intensity);assert.deepEqual(social(s,'xing','me','refuse').record,xr);x.energy=20;const tired=social(s,'xing','me','refuse','quiet',{root:'different-refusal'}).record;assert.ok(tired.intensity>xr.intensity);s.refreshAffect(x,true);s.decide(x);assert.equal(x.decision.rule,'mind*withdraw-briefly');assert.equal(x.action,'rest');evidence.push({case:'personality-and-body',xing:xr,dad:dr,tiredIntensity:tired.intensity,actualCoping:x.action});}finally{s.brain.destroy();}});

test('known constraints differ from breach; relationship domains, reappraisal and emotional decay stay separate',()=>{const s=make();try{freeze(s);const p=s.person('xue');const valid=social(s,p.id,'xing','refuse','help',{explanation:'constrained'}).record;const broken=social(s,p.id,'xing','brokenPromise','quiet').record;assert.equal(valid.judgment,50);assert.equal(broken.judgment,42);assert.equal(broken.emotion,'angry');const corrected=social(s,p.id,'xing','correction','help').record;assert.equal(corrected.emotion,'relieved');assert.equal(p.mental['xing:reliability:quiet'].judgment,42);const t=s.time+300;const faded=s.brain.mindRead(p.id,'xing:reliability:quiet',t,s.domain.affect);assert.equal(faded.active,0);assert.ok(faded.mood>0);assert.equal(faded.record.judgment,42);s.time=t;p.energy=60;s.refreshAffect(p,true);s.decide(p);assert.equal(p.decision.rule,'mind*recover-from-lingering-tension');assert.equal(p.action,'rest');evidence.push({case:'domain-specific-reappraisal',validTrust:50,breachTrust:42,afterFiveHours:{emotion:faded.active,tension:faded.mood,judgment:faded.record.judgment}});}finally{s.brain.destroy();}});

test('save/load retains native belief provenance, emotion clocks, directed judgments and the same intention',()=>{const s=make();let r;try{freeze(s);const p=s.person('xing');s.decide(p);const uid=p.plan.uid;social(s,p.id,'me','brokenPromise');s.time+=35;s.refreshAffect(p,true);const before=p.affect;r=make(decodeSave(encodeSave(s.save())));const q=r.person(p.id);r.refreshAffect(q,true);assert.deepEqual(q.affect,before);assert.equal(q.plan.uid,uid);assert.deepEqual(r.brain.mindRead(p.id,'me:reliability:help',s.time).record,s.brain.mindRead(p.id,'me:reliability:help',s.time).record);evidence.push({case:'portable-native-mind',sameIntent:uid,retainedAffect:true});}finally{s.brain.destroy();r?.brain.destroy();}});

test('personal LLM contexts include only delivered evidence; public tuning has no private minds',()=>{const s=make();try{freeze(s);const a=s.person('xing'),b=s.person('xue');Object.assign(a,{x:0,z:0});Object.assign(b,{x:0,z:-3.4});s.space.screenClosed=true;const secret=s.emit('private-note',a,'这是未透露的打算',[],null,true);const report=buildDayReport(s),xb=reportForModel(report,b.id),xa=reportForModel(report,a.id),world=reportForModel(report);assert.ok(!xb.events.some(e=>e.id===secret.id));assert.ok(xa.events.some(e=>e.id===secret.id));assert.deepEqual(Object.keys(xb.people),[b.id]);assert.ok(!world.people);assert.deepEqual(Object.keys(xb.domain.projects),[b.id]);assert.ok(!JSON.stringify(xb).includes('这是未透露的打算'));evidence.push({case:'reflection-privacy',separatePersonContexts:true});}finally{s.brain.destroy();}});

test('ChatGPT-generated native rule changes coping from the identical lived state and remains conditional',async()=>{
 const seed=make();let saved;try{freeze(seed);const x=seed.person('xing'),me=seed.person('me');Object.assign(x,{x:1,z:0});Object.assign(me,{x:1.4,z:0});social(seed,'xing','me','refuse');seed.refreshAffect(x,true);saved=seed.save();}finally{seed.brain.destroy();}
 const source=fs.readFileSync(new URL('../dist/soar/learned/xing-clarify.soar',import.meta.url),'utf8'),rows=[];
 for(const [patched,energy] of [[false,90],[true,90],[true,25]]){const s=make(saved);try{if(patched)await s.brain.install('xing',source,{author:'ChatGPT',evidence:'own-goal-obstructed-cause-uncertain'});const x=s.person('xing');x.energy=energy;s.decide(x);rows.push({patched,energy,action:s.activeConversation(x)?'chat':x.action,rule:x.decision.rule});assert.equal(s.activeConversation(x)?'chat':x.action,patched&&energy>45?'chat':'rest');if(patched&&energy>45){assert.equal(s.activeConversation(x).topic.kind,'reason');s.advance(12);assert.ok(s.conversations.some(c=>c.turns.some(t=>t.kind==='ask-reason'&&t.from==='xing')));assert.equal(s.brain.recall('me',{type:'event',kind:'conversation-turn',actor:'xing','speech-act':'ask-reason'}).kind,'recalled');}}finally{s.brain.destroy();}}
 evidence.push({case:'actual-authored-coping-rule',sameCheckpoint:true,rows});
});

test('many unique social experiences keep bounded judgments without losing the provenance ledger',()=>{const s=make();try{const p=s.person('xue');for(let i=0;i<22;i++)social(s,p.id,'xing','cooperate','help',{root:'help-'+i});assert.equal(p.mental['xing:reliability:help'].judgment,100);for(let i=0;i<16;i++)social(s,p.id,'xing','brokenPromise','help',{root:'broken-'+i});assert.equal(p.mental['xing:reliability:help'].judgment,0);assert.ok(p.mental['xing:reliability:help'].origin.includes('help-0'));}finally{s.brain.destroy();}});

test('asking why elicits a native recorded reason and actually repairs the specific appraisal',()=>{const s=make();try{freeze(s);const dad=s.person('dad'),x=s.person('xing');Object.assign(dad,{x:4.1,z:3.4});Object.assign(x,{x:4.7,z:3.4});s.start(x,{kind:'studyTable'});s.beginDoing(x);const request={kind:'help',from:dad.id};const answer=s.brain.decide(x.id,s.facts(x,'response',request),s.affordances(x,'response',request));assert.equal(answer.kind,'decline');assert.equal(answer['goal-threat'],'yes');x.lastResponse={...answer,from:dad.id,request:'help',at:s.time};social(s,dad.id,x.id,'refuse','help',{explanation:'unknown',root:'partial-response'});s.refreshAffect(dad,true);s.decide(dad);assert.equal(s.activeConversation(dad).topic.kind,'reason');x.task.remaining=1;s.advance(14);const revised=dad.mental['xing:reliability:help'];assert.equal(revised.reason,'new-explanation-reappraised');assert.equal(revised.emotion,'relieved');assert.ok(s.conversations.some(c=>c.turns.some(t=>t.kind==='ask-reason')));assert.ok(s.messages.some(m=>m.claim?.value==='correction'&&m.delivered));assert.equal(s.brain.recall(x.id,{type:'event',kind:'conversation-turn',actor:dad.id,'speech-act':'ask-reason'}).kind,'recalled');evidence.push({case:'question-to-reappraisal',response:answer.kind,reason:revised.reason,emotion:revised.emotion});}finally{s.brain.destroy();}});

test('old empty-stock knowledge triggers a real reinspection and a meal instead of indefinite waiting',()=>{const s=make();try{freeze(s);s.time=1112;const p=s.person('xing');Object.assign(p,{x:-5,z:3});s.home.money=0;s.home.food=5;s.home.ingredients=0;s.perceive(p,'pot','stock',0);s.perceive(p,'pantry','stock',0);s.perceive(p,'snacks','stock',0);s.time+=16;s.decide(p);assert.equal(p.decision.rule,'routine*check-the-kitchen-at-mealtime');assert.equal(p.task.kind,'inspect');s.advance(24);assert.ok(p.meals.dinner===s.day);assert.ok(s.events.some(e=>e.type==='taskStarted'&&e.actor===p.id&&e.task==='eat'&&e.time<1155));assert.equal(s.known(p,'pot','stock').source,'seen');assert.ok(s.known(p,'pot','stock').at>1128);evidence.push({case:'recheck-stale-empty-stock',oldBelief:0,actualFood:5,mealStarted:true});}finally{s.brain.destroy();}});

test.after(()=>{root.destroy();fs.writeFileSync(new URL('../research/cognition-verification.json',import.meta.url),JSON.stringify({kernel:'native Soar 9.6.5',apiCalls:0,results:evidence},null,2));});
