import fs from 'node:fs';import test from 'node:test';import assert from 'node:assert/strict';
import {Household,SPOTS} from '../dist/simulation.js';import {SoarController,loadSources} from '../dist/soar/controller.js';import {decodeSave} from '../dist/storage.js';import {applyReflection} from '../dist/reflection.js';
const patch=JSON.parse(fs.readFileSync(new URL('../research/day-2-patch.json',import.meta.url)));
const sources=await loadSources(p=>fs.readFileSync(new URL('../dist/'+p,import.meta.url),'utf8')),root=await SoarController.create(sources,{wasmBinary:fs.readFileSync(new URL('../dist/soar/soar.wasm',import.meta.url))}),saved=decodeSave(fs.readFileSync(new URL('../dist/soar/reflection/checkpoint.json',import.meta.url),'utf8'));
for(const p of Object.values(saved.cognition.people))p.programVersion=3;
const make=()=>new Household(2026,saved, {calendar:false,director:false}).attachBrain(new SoarController(root.native,sources));const results=[];
test('two ChatGPT-authored day-end patches change behavior on identical re-exposure conditions',async()=>{try{
 for(const patched of [false,true]){const s=make();try{
  if(patched)await applyReflection(s,patch);for(const p of s.people)s.release(p);s.time=2880+430;s.home.food=5;s.home.ingredients=1;s.home.clean=100;const me=s.person('me');me.hunger=me.fun=me.energy=me.social=90;s.perceive(me,'pot','stock',5);s.perceive(me,'pantry','stock',1);s.decide(me);results.push({scenario:'meal-before-optional-delivery',patched,action:me.action,rule:me.decision.rule,fired:me.decision.fired,project:me.plan.uid});assert.equal(me.action,patched?'idle':'groceries');if(patched)assert.match(me.explanation.reason,/采购来不及/);
 }finally{s.brain.destroy();}}
 for(const patched of [false,true]){const s=make();try{
  if(!patched)s.brain.remove('dad');for(const p of s.people)s.release(p);s.time=2880+550;s.home.tvQuiet=false;const dad=s.person('dad'),xue=s.person('xue');dad.hunger=dad.energy=dad.fun=90;Object.assign(dad,{x:-6.5,z:2.8});Object.assign(xue,SPOTS.tv);s.command('xue','watch');s.beginDoing(xue);s.start(dad,{kind:'work',why:'受控复现写稿遭遇电视干扰'});s.beginDoing(dad);s.tickTask(dad,4);s.time+=4;s.decide(dad);results.push({scenario:'negotiating-noise',patched,action:dad.action,rule:dad.decision.rule,fired:dad.decision.fired,project:dad.plan.uid});if(patched){const c=s.activeConversation(dad);assert.equal(c.topic.domain,'quiet');assert.equal(dad.suspendedTask.action,'work');for(const p of s.people)p.nextDecision=1e9;s.advance(14);assert.ok(c.turns.some(t=>t.kind==='request'));assert.ok(c.turns.some(t=>t.kind==='respond'));results.at(-1).conversationTurns=c.turns.map(t=>t.kind);}else assert.equal(dad.action,'work');
 }finally{s.brain.destroy();}}
 const tuning=make();try{const r=tuning.reviews.at(-1);await applyReflection(tuning,{schemaVersion:1,requestId:r.report.requestId,baseRuleVersion:tuning.rulesVersion,author:'mechanical test fixture',summary:'验证带点号的效果键可以被世界补丁修改',changes:[{kind:'world',path:'/actions/eat/finish/self.hunger',value:50,reason:'仅验证 tuning 执行，非模型反思质量',evidence:[431]}]});for(const p of tuning.people)tuning.release(p);const p=tuning.person('dad');p.hunger=40;tuning.home.food=1;assert.ok(tuning.command('dad','eat').ok);tuning.beginDoing(p);tuning.tickTask(p,16);assert.equal(p.hunger,90);}finally{tuning.brain.destroy();}
 fs.writeFileSync(new URL('../research/day-reflection-verification.json',import.meta.url),JSON.stringify({source:'Two patches authored by ChatGPT after reading sequential native household day reports. Controlled re-exposure tests measure causal rule effects; they are not spontaneous future stories.',runtimeApiCalls:0,results},null,2));console.log(results.map(({fired,...r})=>r));
}finally{root.destroy();}});
